import type { Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Geist, Geist_Mono, Kodchasan } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const kodchasan = Kodchasan({
  subsets: ['latin'],
  weight: '400', // or other weights if needed
});

export const metadata: Metadata = {
  title: 'CalenterAI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={kodchasan.className} suppressHydrationWarning={true}>
          <header className="flex justify-end items-center ">
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}